"""Pins the generated iOS project's deployment target.

`ios/` is gitignored and regenerated by `flutter create` in CI, so this
can't just be committed as project config. The generated Podfile leaves its
platform line commented out and the Xcode target sits well below what some
pods need, which makes `pod install` fail on an incompatible platform before
anything else is attempted.

google_mlkit_pose_detection requires iOS 15.5; Apple requires >= 15.0 for
App Store Connect uploads. The higher floor wins. Both the Podfile (used to
resolve pods) and the project (used to build the app target) have to agree,
so this sets both.

Usage: python3 tool/set_ios_deployment_target.py 15.5
"""
import re
import sys

PODFILE = "ios/Podfile"
PBXPROJ = "ios/Runner.xcodeproj/project.pbxproj"


def patch_podfile(version):
    with open(PODFILE) as handle:
        src = handle.read()

    line = "platform :ios, '{}'".format(version)
    if re.search(r"^\s*#?\s*platform :ios", src, re.M):
        src = re.sub(r"^\s*#?\s*platform :ios.*$", line, src, count=1, flags=re.M)
    else:
        src = line + "\n" + src

    with open(PODFILE, "w") as handle:
        handle.write(src)


def patch_project(version):
    with open(PBXPROJ) as handle:
        src = handle.read()

    src = re.sub(
        r"IPHONEOS_DEPLOYMENT_TARGET = [0-9.]+;",
        "IPHONEOS_DEPLOYMENT_TARGET = {};".format(version),
        src,
    )

    with open(PBXPROJ, "w") as handle:
        handle.write(src)


def main():
    version = sys.argv[1] if len(sys.argv) > 1 else "15.5"
    patch_podfile(version)
    patch_project(version)
    print("iOS deployment target pinned to {}".format(version))


if __name__ == "__main__":
    main()
