// GENERATED — do not edit by hand. Regenerated by `flutter gen-l10n`
// (which `flutter pub get` runs, because pubspec.yaml sets
// `generate: true`). Checked in so the app also compiles from a
// plain checkout on a machine with no Flutter toolchain.

// ignore_for_file: type=lint

import 'package:intl/intl.dart' as intl;

import 'app_localizations.dart';

/// The translations for fr.
class AppLocalizationsFr extends AppLocalizations {
  AppLocalizationsFr([super.locale = 'fr']);

  @override
  String get commonContinue => 'CONTINUER';

  @override
  String get commonClose => 'Fermer';

  @override
  String inches(int inches) {
    return '${inches} po';
  }

  @override
  String inchesApprox(int inches) {
    return '~${inches} po';
  }

  @override
  String inchesGap(int inches) {
    return '-${inches} po';
  }

  @override
  String get introPanel1Headline => 'DÉCOUVRE TA\nVRAIE DÉTENTE';

  @override
  String get introPanel1Support => 'Filme un saut. On chronomètre ton temps de suspension image par image et on le convertit en pouces — pas de mètre ruban, pas d\'approximation.';

  @override
  String get introPanel2Headline => 'ENTRAÎNE-TOI AVEC\nUN VRAI PLAN';

  @override
  String get introPanel2Support => 'Un programme semaine par semaine adapté à ton niveau, à ton emploi du temps et au matériel que tu as vraiment.';

  @override
  String get introPanel3Headline => 'REGARDE TA\nDÉTENTE MONTER';

  @override
  String get introPanel3Support => 'Chaque saut filmé et chaque séance terminée sont enregistrés : ta progression devient un chiffre, plus une impression.';

  @override
  String get introStartCta => 'C\'EST PARTI';

  @override
  String get goalTitle => 'QUEL EST TON\nOBJECTIF DUNK ?';

  @override
  String get goalSubtitle => 'Choisis tous les objectifs qui te motivent — on construit le chemin.';

  @override
  String get experienceTitle => 'QUELLE EST TON\nEXPÉRIENCE EN\nTRAVAIL DE DÉTENTE ?';

  @override
  String get experienceSubtitle => 'Pas d\'ego ici. Sois honnête pour qu\'on te pousse au bon niveau.';

  @override
  String get positionTitle => 'À QUEL POSTE\nJOUES-TU ?';

  @override
  String get positionSubtitle => 'On adaptera les exercices à ton poste.';

  @override
  String get daysTitle => 'COMBIEN DE JOURS\nPAR SEMAINE\nPEUX-TU T\'ENTRAÎNER ?';

  @override
  String get daysSubtitle => 'On reste réaliste. La régularité bat l\'intensité.';

  @override
  String get daysBanner => 'Plus de séances par semaine, c\'est plus de volume — choisis ce que tu peux vraiment tenir.';

  @override
  String get daysChipUnit => 'jours';

  @override
  String get locationTitle => 'OÙ VAS-TU\nT\'ENTRAÎNER ?';

  @override
  String get locationSubtitle => 'On te proposera des programmes adaptés à ton matériel.';

  @override
  String get hopsTitle => 'OÙ EN EST TA\nDÉTENTE AUJOURD\'HUI ?';

  @override
  String get hopsSubtitle => 'Sois honnête — c\'est ce qui calibre tout ton plan.';

  @override
  String get heightTitle => 'TA TAILLE';

  @override
  String get heightSubtitle => 'On s\'en sert pour personnaliser ton analyse de saut et l\'estimation de ta détente.';

  @override
  String get heightUnitLabel => 'PIEDS & POUCES';

  @override
  String heightValue(int feet, int inches) {
    return '${feet}\' ${inches}"';
  }

  @override
  String heightValueCompact(int feet, int inches) {
    return '${feet}\'${inches}"';
  }

  @override
  String heightFeetOption(int feet) {
    return '${feet} pi';
  }

  @override
  String heightInchesOption(int inches) {
    return '${inches} po';
  }

  @override
  String get weightTitle => 'TON POIDS';

  @override
  String get savedToAthleteProfile => 'Enregistré dans ton profil athlète.';

  @override
  String get weightUnitLabel => 'LBS';

  @override
  String get ageTitle => 'TON ÂGE';

  @override
  String get ageUnitLabel => 'ANS';

  @override
  String ageOption(int years) {
    return '${years} ans';
  }

  @override
  String get dunkHandTitle => 'AVEC QUELLE MAIN\nDUNKES-TU ?';

  @override
  String get dunkHandSubtitle => 'Cela fixe la marge au-dessus de l\'arceau dont ton finish a besoin.';

  @override
  String dunkHandClearanceNote(int inches) {
    return 'Un dunk à une main demande de passer le ballon et une main au-dessus de l\'arceau. Les deux avant-bras au-dessus, c\'est environ ${inches} po de plus : un finish à deux mains relève ta cible.';
  }

  @override
  String get commitmentTitle => 'À QUEL POINT ES-TU\nENGAGÉ DANS TON OBJECTIF ?';

  @override
  String get commitmentSubtitle => 'Les athlètes qui s\'engagent avant de commencer sont ceux qui franchissent le palier.';

  @override
  String get gapBasedOnReach => 'D\'APRÈS TON EXTENSION + TA DÉTENTE';

  @override
  String get gapBasedOnHeight => 'D\'APRÈS TA TAILLE + TA DÉTENTE';

  @override
  String get gapTitle => 'VOILÀ L\'ÉCART.';

  @override
  String gapIntro(String height, int current, int target) {
    return 'Tu mesures ${height}. Environ ${current} po aujourd\'hui. Dunker demande en général ~${target} po.';
  }

  @override
  String gapTwoHandNote(int inches) {
    return 'Tu as choisi un finish à deux mains, qui demande les deux avant-bras au-dessus de l\'arceau — environ ${inches} po de plus qu\'un dunk à une main. Ta cible en tient compte.';
  }

  @override
  String gapEstimatedReachNote(int reach) {
    return 'Basé sur une extension debout estimée à ${reach} po d\'après ta taille. Mesure ta vraie extension — dans les Réglages, à tout moment — pour une cible exacte.';
  }

  @override
  String get gapMeterToday => 'AUJOURD\'HUI';

  @override
  String get gapMeterGap => 'ÉCART EST.';

  @override
  String get gapMeterDunk => 'DUNK';

  @override
  String get gapRowHeight => 'Taille';

  @override
  String get gapRowStandingReach => 'Extension debout';

  @override
  String get gapRowEstToday => 'Est. aujourd\'hui';

  @override
  String get gapRowDunkTarget => 'Cible dunk';

  @override
  String get gapRowWeight => 'Poids';

  @override
  String get gapRowHops => 'Détente';

  @override
  String get gapRowPrimaryGoal => 'Objectif principal';

  @override
  String get gapRowTrainingDays => 'Jours d\'entraînement';

  @override
  String gapReachEstimatedSuffix(int reach) {
    return '${reach} po (est.)';
  }

  @override
  String gapWeightValue(int pounds) {
    return '${pounds} lbs';
  }

  @override
  String gapTrainingDaysValue(int days) {
    return '${days}/semaine';
  }

  @override
  String get gapDefaultGoal => 'Ton premier dunk';

  @override
  String get gapCta => 'COMBLER L\'ÉCART';

  @override
  String get potentialTitle => 'TON POTENTIEL DE DÉTENTE';

  @override
  String get potentialSubtitle => 'Projection d\'après ta taille, ta détente et ton rythme d\'entraînement.';

  @override
  String potentialWeekLabel(int week) {
    return 'SEM ${week}';
  }

  @override
  String get potentialWindowLabel => 'PROJECTION SUR 8 SEMAINES';

  @override
  String potentialFromToday(int inches) {
    return 'Potentiel à partir d\'une est. de ~${inches} po aujourd\'hui.';
  }

  @override
  String get potentialCta => 'VOIR MON PLAN';

  @override
  String get howItWorksTitle => 'COMMENT TA DÉTENTE\nEST MESURÉE';

  @override
  String get howItWorksSubtitle => 'Pas de capteur, pas de repère au sol. Juste la physique et l\'appareil photo de ton téléphone.';

  @override
  String get hangTimeLabel => 'TEMPS DE SUSPENSION';

  @override
  String get hangTimeDecides => 'détermine ta hauteur';

  @override
  String get hangTimeFormula => 'plus longtemps en l\'air  =  saut plus haut';

  @override
  String get hangTimeNote => 'Deux athlètes avec le même temps de suspension ont sauté à la même hauteur. C\'est exactement ce qu\'on mesure.';

  @override
  String get howItWorksPoint1Title => 'On suit ton corps, pas les pixels';

  @override
  String get howItWorksPoint1Body => 'Le suivi sur ton appareil traque tes pieds image par image et repère les instants précis où ils quittent le sol puis le retrouvent.';

  @override
  String get howItWorksPoint2Title => 'Mesuré, pas deviné';

  @override
  String get howItWorksPoint2Body => 'Ton temps de suspension donne ta hauteur par la seule gravité — sans calibrage de caméra, sans repère, sans estimation à l\'œil.';

  @override
  String get howItWorksPoint3Title => 'Un plan que tu peux vraiment suivre';

  @override
  String get howItWorksPoint3Body => 'Ton expérience, tes jours d\'entraînement et le fait d\'avoir une salle ou non déterminent ton programme — aucun exercice à la barre si tu t\'entraînes chez toi.';

  @override
  String get howItWorksPoint4Title => 'Une progression vérifiable';

  @override
  String get howItWorksPoint4Body => 'Chaque séance et chaque saut analysé sont enregistrés : la tendance que tu vois est ton propre historique, pas un chiffre de motivation.';

  @override
  String get howItWorksCta => 'LANCER MON PLAN';

  @override
  String get buildingPlanTitle => 'CONSTRUCTION DE TON PLAN';

  @override
  String buildingPlanSubtitle(String program) {
    return 'On t\'associe au programme ${program}';
  }

  @override
  String get planRevealTitle => 'VOILÀ TON PLAN';

  @override
  String get planRevealSubtitle => 'Adapté à ton niveau, à ton emploi du temps et à l\'endroit où tu t\'entraînes.';

  @override
  String planBadgeDays(int days) {
    return '${days} JOURS';
  }

  @override
  String planBadgeWeeks(int weeks) {
    return '${weeks} SEMAINES';
  }

  @override
  String get planThisWeek => 'CETTE SEMAINE';

  @override
  String planDayLabel(int day) {
    return 'JOUR ${day}';
  }

  @override
  String get planDayFoundation => 'FONDATIONS';

  @override
  String get planDayBasic => 'BASES';

  @override
  String get planDayCore => 'SOCLE';

  @override
  String get planDayPower => 'PUISSANCE';

  @override
  String get planDayReactive => 'RÉACTIVITÉ';

  @override
  String get planDayRest => 'REPOS';

  @override
  String get mockJumpAnalysis => 'ANALYSE DE SAUT';

  @override
  String get mockEstVert => 'DÉTENTE EST.';

  @override
  String mockToDunk(int inches) {
    return '${inches} PO POUR DUNKER';
  }

  @override
  String get mockFormScores => 'SCORES TECHNIQUES';

  @override
  String get mockJumpBreakdown => 'ANALYSE DÉTAILLÉE';

  @override
  String get mockWeekDay => 'SEMAINE 2 · JOUR 2 SUR 3';

  @override
  String get mockTodayPower => 'AUJOURD\'HUI · PUISSANCE';

  @override
  String get mockMiniBadgeDays => '3 JOURS';

  @override
  String get mockMiniBadgeGym => 'SALLE';

  @override
  String get mockMiniBadgeWeeks => '8 SEMAINES';

  @override
  String get mockProgress => 'PROGRESSION';

  @override
  String get mockCurrentVertical => 'DÉTENTE ACTUELLE';

  @override
  String mockSinceFirstTest(int inches) {
    return '+${inches} PO DEPUIS LE 1ER TEST';
  }

  @override
  String get mockWorkouts => 'SÉANCES';

  @override
  String get mockDayStreak => 'JOURS D\'AFFILÉE';

  @override
  String get paywallHeadline => 'DÉCROCHE TON\nPREMIER DUNK.';

  @override
  String paywallPlanBuilt(int days) {
    return 'Ton plan de ${days} jours est prêt. Annulable à tout moment.';
  }

  @override
  String paywallPlanBuiltWithTrial(int days, String trial) {
    return 'Ton plan de ${days} jours est prêt. ${trial} offert. Annulable à tout moment.';
  }

  @override
  String get paywallBenefit1Title => 'Ta détente, mesurée';

  @override
  String get paywallBenefit1Body => 'Analyse complète du saut — estimation de détente, écart jusqu\'à ton objectif et conseils';

  @override
  String get paywallBenefit2Title => 'Semaine 1, prête tout de suite';

  @override
  String get paywallBenefit2Body => 'Ton plan personnalisé démarre dès que tu débloques l\'app';

  @override
  String get paywallBenefit3Title => 'Chaque pouce suivi';

  @override
  String get paywallBenefit3Body => 'Suis ta progression vers ton objectif, semaine après semaine';

  @override
  String get paywallCancelAnytime => 'Annulable à tout moment.';

  @override
  String get paywallNoCommitment => 'Sans engagement. Annulable à tout moment.';

  @override
  String get paywallCtaContinueWithoutPurchase => 'CONTINUER SANS ACHAT';

  @override
  String get paywallCtaUnavailable => 'INDISPONIBLE';

  @override
  String get paywallPreviewBuildNote => 'Version de démonstration — les achats ne sont pas encore configurés : l\'app se débloque sans aucun paiement.';

  @override
  String get paywallDebugBuildNote => 'Version de développement — rien ne sera facturé.';

  @override
  String get paywallNoPurchasesInBuild => 'Les achats ne sont pas disponibles dans cette version.';

  @override
  String get paywallDisclosureNoConfig => 'Cette version n\'a aucune configuration d\'achat : rien n\'est en vente et rien ne sera facturé.';

  @override
  String get paywallDisclosureLoadFailed => 'Les formules d\'abonnement n\'ont pas pu être chargées. Rien n\'a été facturé.';

  @override
  String get paywallDisclosureUnavailable => 'Les achats sont indisponibles dans cette version.';

  @override
  String get paywallPlansUnavailableTitle => 'Formules indisponibles';

  @override
  String get paywallPurchasesUnavailableTitle => 'Achats indisponibles dans cette version';

  @override
  String get paywallPlansUnavailableBody => 'Impossible de joindre l\'App Store pour charger les prix des abonnements. Rien n\'a été facturé.';

  @override
  String get paywallPurchasesUnavailableBody => 'Cette version a été compilée sans identifiants d\'achat : il n\'y a rien à acheter ici.';

  @override
  String get paywallTryAgain => 'Réessayer';

  @override
  String get paywallBestValue => 'MEILLEURE OFFRE';

  @override
  String paywallSavePercent(int percent) {
    return 'Économise ${percent} %';
  }

  @override
  String get paywallViewOtherPlans => 'Voir les autres formules';

  @override
  String get paywallRestorePurchases => 'Restaurer les achats';

  @override
  String get paywallPrivacy => 'Confidentialité';

  @override
  String get paywallTerms => 'Conditions';

  @override
  String get paywallPrivacyPolicyTitle => 'Politique de confidentialité';

  @override
  String get paywallTermsOfUseTitle => 'Conditions d\'utilisation';

  @override
  String get paywallPageNotPublished => 'Cette page n\'est pas encore publiée.';

  @override
  String paywallCouldNotOpenLegal(String title, String url) {
    return 'Impossible d\'ouvrir ${title}. L\'adresse est ${url}';
  }

  @override
  String get paywallErrorNotEntitled => 'L\'achat a bien été effectué mais n\'a pas débloqué DunkIt. Essaie « Restaurer les achats », ou contacte le support — rien n\'est perdu.';

  @override
  String get paywallErrorUnavailable => 'Les achats sont indisponibles pour le moment. Réessaie plus tard.';

  @override
  String get paywallErrorFailed => 'L\'achat n\'a pas pu aboutir. Vérifie ta connexion et réessaie.';

  @override
  String get paywallErrorNothingToRestore => 'Aucun abonnement DunkIt actif trouvé sur cet identifiant Apple.';

  @override
  String get commonCancel => 'Annuler';

  @override
  String get commonSave => 'Enregistrer';

  @override
  String get weekdayInitials => 'L,M,M,J,V,S,D';

  @override
  String inchesPlus(int inches) {
    return '+${inches} po';
  }

  @override
  String get tabHome => 'ACCUEIL';

  @override
  String get tabAnalyze => 'ANALYSE';

  @override
  String get tabTrain => 'SÉANCE';

  @override
  String get tabFeed => 'CLASSEMENT';

  @override
  String get tabProgress => 'PROGRÈS';

  @override
  String get settingsTitle => 'RÉGLAGES';

  @override
  String get settingsLeaderboardName => 'Nom au classement';

  @override
  String get settingsStandingReach => 'Extension debout';

  @override
  String get settingsRetakeOnboarding => 'Refaire le questionnaire';

  @override
  String get settingsNotSet => 'Non renseigné';

  @override
  String get retakeOnboardingTitle => 'Refaire le questionnaire ?';

  @override
  String get retakeOnboardingBody => 'Cela efface ton profil actuel et te fait reprendre le questionnaire depuis le début.';

  @override
  String get retakeOnboardingConfirm => 'Refaire';

  @override
  String get standingReachHowTo => 'Colle-toi bien droit contre un mur, tends un bras le plus haut possible, marque le bout de tes doigts, puis mesure depuis le sol. Ta cible de dunk repose sur ce chiffre.';

  @override
  String standingReachValue(String label, int inches) {
    return '${label}  ·  ${inches} po';
  }

  @override
  String standingReachEstimateNote(String label) {
    return 'Actuellement estimée à ${label} d\'après ta taille.';
  }

  @override
  String homeDayCounter(int session, int total) {
    return 'JOUR ${session}/${total}';
  }

  @override
  String get homeTodayBadge => 'AUJOURD\'HUI';

  @override
  String get homeProgramComplete => 'PROGRAMME TERMINÉ';

  @override
  String get homeProgramCompleteBody => 'Tu as bouclé toutes les séances — beau travail.';

  @override
  String homeFocusDay(String focus) {
    return 'JOUR ${focus}';
  }

  @override
  String homeWeekSession(int week, int session, int total) {
    return 'Semaine ${week} • Séance ${session}/${total}';
  }

  @override
  String get homeCtaViewTrain => 'VOIR LES SÉANCES';

  @override
  String get homeCtaStartSession => 'LANCER LA SÉANCE';

  @override
  String get homeLatestVert => 'DERNIÈRE DÉTENTE';

  @override
  String get homeDayStreak => 'JOURS D\'AFFILÉE';

  @override
  String jumpDateShort(DateTime date) {
    final intl.DateFormat dateDateFormat =
        intl.DateFormat.Md(localeName);
    final String dateString = dateDateFormat.format(date);
    return '${dateString}';
  }

  @override
  String jumpDateFull(DateTime date) {
    final intl.DateFormat dateDateFormat =
        intl.DateFormat.yMd(localeName);
    final String dateString = dateDateFormat.format(date);
    return '${dateString}';
  }

  @override
  String get progressTitle => 'PROGRESSION';

  @override
  String get progressTrendTitle => 'ÉVOLUTION DE LA DÉTENTE';

  @override
  String get progressTrendEmpty => 'Enregistre quelques sauts de plus pour voir ta tendance';

  @override
  String get progressRecentAnalyses => 'ANALYSES RÉCENTES';

  @override
  String get progressViewAll => 'Tout voir';

  @override
  String get progressCurrentVertical => 'DÉTENTE ACTUELLE';

  @override
  String get progressVertUnitSuffix => '  po';

  @override
  String get progressLogFirstJump => 'Enregistre ton premier test pour commencer le suivi';

  @override
  String get progressGoToAnalyze => 'Aller à Analyse';

  @override
  String progressSinceFirstGain(int inches) {
    return '+${inches} po depuis ton premier test';
  }

  @override
  String progressSinceFirstLoss(int inches) {
    return '${inches} po depuis ton premier test';
  }

  @override
  String get progressSinceFirstNoChange => 'Aucun changement depuis ton premier test';

  @override
  String get progressWorkouts => 'SÉANCES';

  @override
  String get progressCompleted => 'TERMINÉES';

  @override
  String get progressRemaining => 'RESTANTES';

  @override
  String get progressCompleteLabel => 'ACCOMPLI';

  @override
  String progressPercent(int percent) {
    return '${percent} %';
  }

  @override
  String get progressDayStreak => 'JOURS D\'AFFILÉE';

  @override
  String get progressStreakDaysSuffix => '  jours';

  @override
  String get jumpHistoryTitle => 'Historique des sauts';

  @override
  String get jumpHistoryEmpty => 'Aucun saut enregistré pour l\'instant.';

  @override
  String jumpVideoTitle(int inches, DateTime date) {
    final intl.DateFormat dateDateFormat =
        intl.DateFormat.yMd(localeName);
    final String dateString = dateDateFormat.format(date);
    return '${inches} po · ${dateString}';
  }

  @override
  String get jumpVideoLoadError => 'Impossible de charger cette vidéo.';

  @override
  String get jumpVideoMissing => 'Cette vidéo n\'est plus sur ton appareil.';

  @override
  String get jumpVideoShareFailed => 'Impossible d\'ouvrir le menu de partage. Réessaie.';

  @override
  String jumpShareText(int inches) {
    return '${inches} po de détente — Dunk It';
  }

  @override
  String get weekdayLabels => 'LUN,MAR,MER,JEU,VEN,SAM,DIM';

  @override
  String get trainTitle => 'SÉANCE';

  @override
  String get trainEnrolledProgram => 'PROGRAMME EN COURS';

  @override
  String trainPositionLabel(int week, int day, int sessionsPerWeek) {
    return 'SEMAINE ${week} · JOUR ${day} SUR ${sessionsPerWeek}';
  }

  @override
  String trainProgramMeta(String position, int weeks) {
    return '${position} • ${weeks} SEMAINES';
  }

  @override
  String get trainDeloadPill => 'DÉCHARGE';

  @override
  String get trainDeloadExplainer => 'Semaine de décharge : moins de volume, volontairement. C\'est pendant les semaines allégées que le travail déjà fait se transforme en détente.';

  @override
  String trainWeekNumber(int week) {
    return 'SEMAINE ${week}';
  }

  @override
  String trainWeekSummary(int sessions, int rest) {
    return '${sessions} séances • ${rest} repos';
  }

  @override
  String get trainRestDayTitle => 'JOUR DE REPOS';

  @override
  String get trainRestDaySubtitle => 'Tu t\'es déjà entraîné aujourd\'hui.';

  @override
  String get trainRestDayBody => 'La détente se construit entre les séances, pas pendant. Dors, mange, et laisse les tendons récupérer.';

  @override
  String trainUpNext(String focus) {
    return 'Prochaine séance : JOUR ${focus}';
  }

  @override
  String get trainTodaysExercises => 'EXERCICES DU JOUR';

  @override
  String trainExerciseCount(num count) {
    final String pluralised = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      one: '${count} exercice',
      other: '${count} exercices',
    );
    return pluralised;
  }

  @override
  String trainFocusAndWarmUp(String focus, String warmUp) {
    return '${focus} • ${warmUp}';
  }

  @override
  String get trainDeloadVolumeNote => 'Le volume est réduit cette semaine — mêmes mouvements, moins de séries.';

  @override
  String get trainProgramProgress => 'AVANCEMENT DU PROGRAMME';

  @override
  String get trainCtaProgramComplete => 'PROGRAMME TERMINÉ';

  @override
  String get trainCtaTrainAnyway => 'M\'ENTRAÎNER QUAND MÊME';

  @override
  String get trainCtaStartSession => 'LANCER LA SÉANCE DU JOUR';

  @override
  String get warmUpHeader => 'ÉCHAUFFEMENT';

  @override
  String warmUpFocusDay(String focus) {
    return 'JOUR ${focus}';
  }

  @override
  String get warmUpDeloadNote => 'SEMAINE DE DÉCHARGE — moins de séries, volontairement. C\'est là que l\'adaptation se fait.';

  @override
  String get warmUpCardLabel => 'ÉCHAUFFEMENT';

  @override
  String get warmUpCta => 'COMMENCER LES EXERCICES';

  @override
  String logExerciseCounter(int index, int total) {
    return 'EXERCICE ${index}/${total}';
  }

  @override
  String get logGuideTitle => 'COMMENT L\'EXÉCUTER';

  @override
  String logGuideSubtitle(int steps) {
    return '${steps} étapes, erreurs fréquentes et ce que ça travaille.';
  }

  @override
  String get logGuideNone => 'Pas encore de consignes pour cet exercice.';

  @override
  String get logSwappedForHome => 'Adapté à ton matériel à la maison';

  @override
  String logSwappedForHomeReplaces(String original) {
    return 'Adapté à ton matériel à la maison — remplace ${original}';
  }

  @override
  String logSetNumber(int number) {
    return 'SÉRIE ${number}';
  }

  @override
  String get logRepsHint => 'reps';

  @override
  String get logWeightHint => 'lbs (facultatif)';

  @override
  String get logValidated => 'FAIT';

  @override
  String get logValidate => 'VALIDER';

  @override
  String get logCtaFinishSession => 'TERMINER LA SÉANCE';

  @override
  String get logCtaNextExercise => 'EXERCICE SUIVANT';

  @override
  String get logValidateEverySet => 'Valide chaque série pour continuer';

  @override
  String get sessionCompleteTitle => 'SÉANCE TERMINÉE';

  @override
  String get sessionCompleteSubtitle => 'Beau travail. Voici ce que tu as enregistré.';

  @override
  String sessionCompleteRow(String exercise, int sets, int reps) {
    return '${exercise} : ${sets} séries, ${reps} reps';
  }

  @override
  String get sessionCompleteCta => 'ENREGISTRER ET TERMINER';

  @override
  String get exerciseGuideHeader => 'FICHE EXERCICE';

  @override
  String get exerciseGuideWhyItMatters => 'POURQUOI C\'EST IMPORTANT';

  @override
  String get exerciseGuideHowToDoIt => 'COMMENT L\'EXÉCUTER';

  @override
  String get exerciseGuideCommonMistakes => 'ERREURS FRÉQUENTES';

  @override
  String get exerciseGuideWhatItTrains => 'CE QUE ÇA TRAVAILLE';

  @override
  String get exerciseGuideSwappedTitle => 'ADAPTÉ À TON MATÉRIEL À LA MAISON';

  @override
  String get exerciseGuideSwappedBody => 'L\'exercice prévu demande du matériel que tu n\'as pas indiqué. Celui-ci travaille la même qualité avec rien d\'autre que le sol.';

  @override
  String exerciseGuideSwappedBodyNamed(String original) {
    return 'Remplace ${original}, qui demande du matériel que tu n\'as pas indiqué. Celui-ci travaille la même qualité avec rien d\'autre que le sol.';
  }

  @override
  String get exerciseGuideEmpty => 'Aucune consigne n\'a encore été rédigée pour cet exercice.';

  @override
  String get exerciseGuideNoDemoTitle => 'PAS ENCORE DE VIDÉO';

  @override
  String get exerciseGuideNoDemoBody => 'Rien n\'a été filmé pour cet exercice. Les étapes ci-dessous constituent l\'intégralité des consignes.';

  @override
  String get exerciseGuideFramePosition => 'POSITION';

  @override
  String get exerciseGuideFrameStart => 'DÉPART';

  @override
  String get exerciseGuideFrameFinish => 'FIN';

  @override
  String get exerciseGuideFrameDisclaimer => 'Photos de référence, pas un enregistrement de ton propre saut.';

  @override
  String jumpDateMedium(DateTime date) {
    final intl.DateFormat dateDateFormat =
        intl.DateFormat.yMMMd(localeName);
    final String dateString = dateDateFormat.format(date);
    return '${dateString}';
  }

  @override
  String get feedTitle => 'CLASSEMENTS';

  @override
  String get feedGlobalTitle => 'MEILLEURES DÉTENTES';

  @override
  String get feedGlobalSubtitle => 'Tous les athlètes DunkIt, classés selon leur meilleur saut mesuré.';

  @override
  String get feedPersonalTitle => 'TES MEILLEURS SAUTS';

  @override
  String get feedPersonalSubtitle => 'Tous tes sauts analysés, classés par détente.';

  @override
  String get feedNotConfiguredTitle => 'Classement mondial désactivé dans cette version';

  @override
  String get feedNotConfiguredBody => 'Cette version de l\'app a été compilée sans identifiants de classement : il n\'y a rien à joindre. Tout le reste fonctionne hors ligne.';

  @override
  String get feedUnavailableTitle => 'Classement mondial injoignable';

  @override
  String get feedUnavailableBody => 'Vérifie ta connexion et tire vers le bas pour réessayer. Tes propres sauts ci-dessous sont stockés sur cet appareil et ne sont pas affectés.';

  @override
  String get feedNoAthletesTitle => 'Aucun athlète classé pour l\'instant';

  @override
  String get feedNoAthletesBody => 'Personne n\'a encore publié de saut mesuré. Analyse le tien et tu prends la première place.';

  @override
  String get feedLoading => 'Chargement du classement mondial…';

  @override
  String get feedYouBadge => 'TOI';

  @override
  String feedJumpStat(int inches) {
    return '${inches} po de détente';
  }

  @override
  String feedAttemptSeparator(String attempt) {
    return ' · ${attempt}';
  }

  @override
  String get feedAttemptFallback => 'Saut';

  @override
  String feedGlobalStatSeparator(String height) {
    return ' · ${height}';
  }

  @override
  String feedRankNumber(int rank) {
    return 'n°${rank}';
  }

  @override
  String get feedEmptyPersonalTitle => 'Aucun saut classé pour l\'instant';

  @override
  String get feedEmptyPersonalBody => 'Analyse ton premier saut pour lancer ton classement.';

  @override
  String get feedNamePromptTitle => 'Tu n\'es pas encore au classement';

  @override
  String get feedNamePromptBody => 'Choisis un nom et ton meilleur saut mesuré sera classé avec tous les autres. Seuls le nom, la détente et ta taille sont partagés — jamais tes vidéos.';

  @override
  String get feedSetBoardName => 'CHOISIR MON NOM';

  @override
  String get displayNameTitle => 'Ton nom au classement';

  @override
  String get displayNameBody => 'C\'est la seule chose que les autres athlètes voient. Tes vidéos ne quittent jamais ce téléphone.';

  @override
  String get displayNameHint => 'ex. Marcus';

  @override
  String get scoreBounce => 'REBOND';

  @override
  String get scorePower => 'PUISSANCE';

  @override
  String get scoreControl => 'CONTRÔLE';

  @override
  String get scoreForm => 'TECHNIQUE';

  @override
  String get analyzeTitle => 'ANALYSE';

  @override
  String get analyzeIntro => 'Filme ton saut de face, corps entier dans le cadre. On suit tes pieds pour chronométrer le vol, puis la gravité donne la hauteur — aucun calibrage nécessaire.';

  @override
  String get analyzePickError => 'Impossible d\'accéder à l\'appareil photo ou à la galerie.';

  @override
  String get analyzeBusyCta => 'UNE SECONDE…';

  @override
  String get analyzeRecordCta => 'FILMER UN SAUT';

  @override
  String get analyzeChooseLibrary => 'Choisir dans la galerie';

  @override
  String get analyzeSkip => 'Je ferai ça plus tard';

  @override
  String get analyzeSkipSubtitle => 'Tu peux analyser un saut à tout moment depuis l\'app.';

  @override
  String get trimTitle => 'DÉCOUPER LA VIDÉO';

  @override
  String get trimCancel => 'ANNULER';

  @override
  String get trimHintDrag => 'Fais glisser les poignées sur la timeline pour découper.';

  @override
  String get trimHintRange => 'Début / Fin — ajuste sur un seul saut ou dunk pour une meilleure analyse.';

  @override
  String get trimStartLabel => 'DÉBUT :';

  @override
  String get trimEndLabel => 'FIN :';

  @override
  String get trimAnalyzeCta => 'ANALYSER';

  @override
  String get trimRetake => 'Refilmer';

  @override
  String get trimLoadError => 'Impossible de charger cette vidéo.';

  @override
  String get trimTryAgain => 'RÉESSAYER';

  @override
  String get processingHeadline => 'ANALYSE';

  @override
  String get processingHeadlineAccent => ' DE TON SAUT';

  @override
  String get processingBadge => 'TRAITEMENT IA';

  @override
  String get processingStepTracking => 'Suivi de ton corps sur la vidéo';

  @override
  String get processingStepLocating => 'Repérage de l\'impulsion et de la réception';

  @override
  String get processingStepEstimating => 'Estimation de ta détente';

  @override
  String get processingFallbackMotion => 'Le suivi corporel n\'a pas pu fonctionner sur cette vidéo — passage à l\'analyse du mouvement image par image.';

  @override
  String processingFallbackDeclined(String reason) {
    return 'Le suivi corporel n\'a pas pu mesurer cette vidéo (${reason}).';
  }

  @override
  String get unmeasuredTitle => 'AUCUNE MESURE';

  @override
  String get unmeasuredSubtitle => 'On préfère te le dire plutôt que d\'inventer un chiffre.';

  @override
  String get unmeasuredNoWindowHeadline => 'On t\'a bien suivi, mais tes pieds n\'ont jamais clairement quitté le sol.';

  @override
  String get unmeasuredNoWindowFix1 => 'Découpe la vidéo pour ne garder que le saut et un instant de chaque côté.';

  @override
  String get unmeasuredNoWindowFix2 => 'Garde tes pieds dans le cadre du début à la fin — c\'est eux qu\'on chronomètre.';

  @override
  String get unmeasuredNoWindowFix3 => 'Filme de profil ou de face, pas en plongée.';

  @override
  String get unmeasuredLostTrackHeadline => 'On n\'a pas réussi à te suivre sur toute la vidéo.';

  @override
  String get unmeasuredLostTrackFix1 => 'Mets tout ton corps dans le cadre, de la tête aux pieds.';

  @override
  String get unmeasuredLostTrackFix2 => 'Plus de lumière aide — le suivi galère dans un gymnase sombre.';

  @override
  String get unmeasuredLostTrackFix3 => 'Évite un arrière-plan chargé juste derrière toi.';

  @override
  String get unmeasuredGappyHeadline => 'On t\'a perdu en plein milieu du saut.';

  @override
  String get unmeasuredGappyFix1 => 'Recule pour que tout ton corps reste dans le cadre au point haut.';

  @override
  String get unmeasuredGappyFix2 => 'Garde le téléphone immobile — suivre le saut vers le haut te fait sortir du cadre.';

  @override
  String get unmeasuredGappyFix3 => 'Plus de lumière réduit le flou de mouvement à l\'impulsion.';

  @override
  String get unmeasuredSmallJumpHeadline => 'Le saut de cette vidéo est trop petit pour être chronométré de façon fiable.';

  @override
  String get unmeasuredSmallJumpFix1 => 'Découpe sur ton meilleur essai si la vidéo en contient plusieurs.';

  @override
  String get unmeasuredSmallJumpFix2 => 'Filme un saut à pleine intensité — un petit saut d\'échauffement est sous notre seuil de mesure.';

  @override
  String get unmeasuredImplausibleHeadline => 'Le temps de vol mesuré sort de ce qu\'un vrai saut peut donner.';

  @override
  String get unmeasuredImplausibleFix1 => 'Découpe au plus près d\'un seul saut.';

  @override
  String get unmeasuredImplausibleFix2 => 'Vérifie que la vidéo est en vitesse normale — le ralenti fausse le chronométrage.';

  @override
  String get unmeasuredTooShortHeadline => 'La vidéo est trop courte pour être analysée.';

  @override
  String get unmeasuredTooShortFix1 => 'Inclus un instant avant le saut et après la réception.';

  @override
  String get unmeasuredGenericHeadline => 'On n\'a pas pu mesurer cette vidéo.';

  @override
  String get unmeasuredGenericFix1 => 'Découpe au plus près d\'un seul saut et réessaie.';

  @override
  String get unmeasuredRetrimCta => 'DÉCOUPER ET RÉESSAYER';

  @override
  String get unmeasuredNewClip => 'Utiliser une autre vidéo';

  @override
  String get resultTitle => 'TON SAUT';

  @override
  String get resultCtaAnalyzeAnother => 'ANALYSER UN AUTRE SAUT';

  @override
  String get resultEstVert => 'DÉTENTE EST.';

  @override
  String resultClearsDunk(int target) {
    return 'Ça dépasse ta cible de ${target} po pour dunker';
  }

  @override
  String resultGapToDunk(int gap, int target) {
    return '${gap} po avant ta cible de ${target} po pour dunker';
  }

  @override
  String resultEstimatedReachNote(int reach) {
    return 'La cible suppose une extension debout estimée à ${reach} po. Renseigne ta vraie extension dans les Réglages pour une cible exacte.';
  }

  @override
  String get resultFormScoresTitle => 'SCORES TECHNIQUES';

  @override
  String get resultScoresUnavailable => 'Noter ta technique demande le suivi corporel, et il n\'a pas pu te suivre sur cette vidéo.';

  @override
  String get resultScoresIntro => 'Noté à partir de ton corps sur cette vidéo — rien n\'est inventé là où la mesure était impossible.';

  @override
  String get resultScoresDisclaimer => 'Les scores évaluent ta technique par rapport à des repères d\'entraîneur, pas par rapport aux autres athlètes.';

  @override
  String get resultNotMeasured => 'Non mesuré';

  @override
  String get resultNoTrackingReason => 'le suivi corporel n\'a pas fonctionné';

  @override
  String get resultScoreDenominator => '/100';

  @override
  String resultScoreOutOf(int score) {
    return '${score}/100';
  }

  @override
  String get resultBreakdownTitle => 'ANALYSE DÉTAILLÉE';

  @override
  String get resultStrongest => 'POINT FORT';

  @override
  String get resultWeakest => 'POINT FAIBLE';

  @override
  String resultAspectCaption(String caption, String aspect) {
    return '${caption} · ${aspect}';
  }

  @override
  String resultMeasuredPrefix(String measurement) {
    return 'Mesuré : ${measurement}';
  }

  @override
  String get resultHowToWorkOnIt => 'COMMENT TRAVAILLER ÇA';

  @override
  String get resultGeneralTips => 'CONSEILS GÉNÉRAUX POUR COMBLER L\'ÉCART';
}
